services:
  salvemos-los-ecosistemas:
    image: salvemos-los-ecosistemas
    hostname: salvemos-los-ecosistemas
    restart: always
    container_name: salvemos-los-ecosistemas
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: .env
    environment:
      PORT: 3000
      MONGODB_URI: mongodb+srv://cachorro_cami:Tengo1amo@cluster0.ffbyjzl.mongodb.net/?retryWrites=true&w=majority
      NODE_ENV: production
    ports:
      - 5556:3000
    expose:
      - 3000
    networks:
      - internal

networks:
  internal:
    external: true
    name: internal
